services:
  db:
    image: mysql:8.0
    container_name: bedrock_shared_db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - app-network
volumes:
  dbdata:
    driver: local
networks:
  app-network:
    driver: bridge
    name: bedrock_shared_network
