"""Add ssh_password remove panel creds

Revision ID: 16cc5177cf8b
Revises: 8dece49dbc7f
Create Date: 2026-01-13 12:31:31.759672

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import forge.db.custom_types


# revision identifiers, used by Alembic.
revision: str = '16cc5177cf8b'
down_revision: Union[str, Sequence[str], None] = '8dece49dbc7f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def _get_inspector() -> sa.Inspector:
    return sa.inspect(op.get_bind())


def _table_exists(inspector: sa.Inspector, table_name: str) -> bool:
    return table_name in inspector.get_table_names()


def _column_exists(inspector: sa.Inspector, table_name: str, column_name: str) -> bool:
    if not _table_exists(inspector, table_name):
        return False
    return any(column["name"] == column_name for column in inspector.get_columns(table_name))


def _add_columns_if_missing(
    inspector: sa.Inspector,
    table_name: str,
    columns: Sequence[sa.Column],
) -> None:
    for column in columns:
        if not _column_exists(inspector, table_name, column.name):
            op.add_column(table_name, column)


def _drop_columns_if_exist(
    inspector: sa.Inspector,
    table_name: str,
    column_names: Sequence[str],
) -> None:
    for column_name in column_names:
        if _column_exists(inspector, table_name, column_name):
            op.drop_column(table_name, column_name)


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_index(op.f('ix_roles_name'), table_name='roles')
    # op.drop_table('roles')
    # op.drop_index(op.f('ix_permissions_code'), table_name='permissions')
    # op.drop_table('permissions')
    # op.drop_table('user_roles')
    # op.drop_table('role_permissions')
    inspector = _get_inspector()
    _add_columns_if_missing(
        inspector,
        'servers',
        [sa.Column('ssh_password', forge.db.custom_types.EncryptedString(), nullable=True)],
    )
    _drop_columns_if_exist(inspector, 'servers', ['panel_api_user', 'panel_api_token'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    inspector = _get_inspector()
    _add_columns_if_missing(
        inspector,
        'servers',
        [
            sa.Column('panel_api_token', sa.VARCHAR(), nullable=True),
            sa.Column('panel_api_user', sa.VARCHAR(length=100), nullable=True),
        ],
    )
    _drop_columns_if_exist(inspector, 'servers', ['ssh_password'])
    # Tables kept in upgrade, so no creation needed in downgrade
    # ### end Alembic commands ###
