"""Add ssh_password remove panel creds

Revision ID: 16cc5177cf8b
Revises: 8dece49dbc7f
Create Date: 2026-01-13 12:31:31.759672

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import forge.db.custom_types


# revision identifiers, used by Alembic.
revision: str = '16cc5177cf8b'
down_revision: Union[str, Sequence[str], None] = '8dece49dbc7f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_index(op.f('ix_roles_name'), table_name='roles')
    # op.drop_table('roles')
    # op.drop_index(op.f('ix_permissions_code'), table_name='permissions')
    # op.drop_table('permissions')
    # op.drop_table('user_roles')
    # op.drop_table('role_permissions')
    op.add_column('servers', sa.Column('ssh_password', forge.db.custom_types.EncryptedString(), nullable=True))
    op.drop_column('servers', 'panel_api_user')
    op.drop_column('servers', 'panel_api_token')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('servers', sa.Column('panel_api_token', sa.VARCHAR(), nullable=True))
    op.add_column('servers', sa.Column('panel_api_user', sa.VARCHAR(length=100), nullable=True))
    op.drop_column('servers', 'ssh_password')
    # Tables kept in upgrade, so no creation needed in downgrade
    # ### end Alembic commands ###
