"""Add logs to backups

Revision ID: 1eedd00e5efd
Revises: d380adbc04c9
Create Date: 2026-01-26 07:40:58.067417

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1eedd00e5efd'
down_revision: Union[str, Sequence[str], None] = 'd380adbc04c9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('backups', sa.Column('logs', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('backups', 'logs')
    # ### end Alembic commands ###
