"""Add environment_id to backup_schedules

Revision ID: 2ac2bda6090b
Revises: 1eedd00e5efd
Create Date: 2026-01-27 12:13:28.374312

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2ac2bda6090b'
down_revision: Union[str, Sequence[str], None] = '1eedd00e5efd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('backup_schedules', sa.Column('environment_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_backup_schedules_environment_id'), 'backup_schedules', ['environment_id'], unique=False)
    op.create_foreign_key(None, 'backup_schedules', 'project_servers', ['environment_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'backup_schedules', type_='foreignkey')
    op.drop_index(op.f('ix_backup_schedules_environment_id'), table_name='backup_schedules')
    op.drop_column('backup_schedules', 'environment_id')
    # ### end Alembic commands ###
