"""encrypt_ssh_keys_and_tokens

Revision ID: 8dece49dbc7f
Revises: h8i9j0k1l2m3
Create Date: 2026-01-10 10:51:33.244242

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import forge.db.custom_types

# revision identifiers, used by Alembic.
revision: str = '8dece49dbc7f'
down_revision: Union[str, Sequence[str], None] = 'h8i9j0k1l2m3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def _get_inspector() -> sa.Inspector:
    return sa.inspect(op.get_bind())


def _table_exists(inspector: sa.Inspector, table_name: str) -> bool:
    return table_name in inspector.get_table_names()


def _column_exists(inspector: sa.Inspector, table_name: str, column_name: str) -> bool:
    if not _table_exists(inspector, table_name):
        return False
    return any(column["name"] == column_name for column in inspector.get_columns(table_name))


def _index_exists(inspector: sa.Inspector, table_name: str, index_name: str) -> bool:
    if not _table_exists(inspector, table_name):
        return False
    return any(index["name"] == index_name for index in inspector.get_indexes(table_name))


def _add_columns_if_missing(
    inspector: sa.Inspector,
    table_name: str,
    columns: Sequence[sa.Column],
) -> None:
    for column in columns:
        if not _column_exists(inspector, table_name, column.name):
            op.add_column(table_name, column)


def _drop_columns_if_exist(
    inspector: sa.Inspector,
    table_name: str,
    column_names: Sequence[str],
) -> None:
    for column_name in column_names:
        if _column_exists(inspector, table_name, column_name):
            op.drop_column(table_name, column_name)


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    inspector = _get_inspector()
    if not _table_exists(inspector, 'audit_logs'):
        op.create_table('audit_logs',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=True),
        sa.Column('action', sa.Enum('CREATE', 'UPDATE', 'DELETE', 'LOGIN', 'LOGOUT', 'DEPLOY', 'BACKUP', 'RESTORE', 'SYNC', 'PROVISION', 'COMMAND', 'OTHER', name='auditaction'), nullable=False),
        sa.Column('entity_type', sa.String(length=50), nullable=True),
        sa.Column('entity_id', sa.String(length=50), nullable=True),
        sa.Column('details', sa.Text(), nullable=True),
        sa.Column('ip_address', sa.String(length=45), nullable=True),
        sa.Column('user_agent', sa.String(length=255), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
        sa.PrimaryKeyConstraint('id')
        )
    audit_logs_index = op.f('ix_audit_logs_id')
    if _table_exists(inspector, 'audit_logs') and not _index_exists(inspector, 'audit_logs', audit_logs_index):
        op.create_index(audit_logs_index, 'audit_logs', ['id'], unique=False)
    op.alter_column('client_users', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('client_users', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.alter_column('client_users', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    _add_columns_if_missing(
        inspector,
        'clients',
        [
            sa.Column('billing_name', sa.String(length=255), nullable=True),
            sa.Column('city', sa.String(length=100), nullable=True),
            sa.Column('state', sa.String(length=100), nullable=True),
            sa.Column('postal_code', sa.String(length=20), nullable=True),
            sa.Column('country', sa.String(length=100), nullable=False),
            sa.Column('monthly_rate', sa.Float(), nullable=False),
            sa.Column('total_revenue', sa.Float(), nullable=False),
            sa.Column('outstanding_balance', sa.Float(), nullable=False),
            sa.Column('last_invoice_date', sa.Date(), nullable=True),
            sa.Column('last_payment_date', sa.Date(), nullable=True),
            sa.Column('tags', sa.Text(), nullable=True),
            sa.Column('owner_id', sa.Integer(), nullable=False),
        ],
    )
    op.alter_column('clients', 'billing_status',
               existing_type=postgresql.ENUM('ACTIVE', 'INACTIVE', 'TRIAL', 'OVERDUE', name='billingstatus'),
               nullable=False)
    op.alter_column('clients', 'payment_terms',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=50),
               nullable=False)
    op.alter_column('clients', 'currency',
               existing_type=sa.VARCHAR(length=3),
               nullable=False)
    op.alter_column('clients', 'tax_rate',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('clients', 'auto_billing',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('clients', 'invoice_prefix',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.alter_column('clients', 'next_invoice_number',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('clients', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('clients', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.drop_constraint(op.f('clients_email_key'), 'clients', type_='unique')
    clients_email_index = op.f('ix_clients_email')
    if _index_exists(inspector, 'clients', clients_email_index):
        op.drop_index(clients_email_index, table_name='clients')
        inspector = _get_inspector()
    if not _index_exists(inspector, 'clients', clients_email_index):
        op.create_index(clients_email_index, 'clients', ['email'], unique=False)
    op.create_foreign_key(None, 'clients', 'users', ['owner_id'], ['id'])
    _drop_columns_if_exist(inspector, 'clients', ['website', 'monthly_retainer', 'contract_terms'])
    op.alter_column('domains', 'registrar',
               existing_type=postgresql.ENUM('NAMECHEAP', 'GODADDY', 'CLOUDFLARE', 'GOOGLE_DOMAINS', 'NAME_COM', 'PORKBUN', 'HOVER', 'DYNADOT', 'OTHER', name='registrar'),
               nullable=False)
    op.alter_column('domains', 'status',
               existing_type=postgresql.ENUM('ACTIVE', 'EXPIRED', 'PENDING_TRANSFER', 'LOCKED', 'REDEMPTION', 'PENDING_DELETE', name='domainstatus'),
               nullable=False)
    op.alter_column('domains', 'auto_renew',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('domains', 'privacy_protection',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('domains', 'transfer_lock',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('domains', 'annual_cost',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('domains', 'currency',
               existing_type=sa.VARCHAR(length=3),
               nullable=False)
    op.alter_column('domains', 'reminder_days',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('domains', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('domains', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.drop_constraint(op.f('domains_domain_name_key'), 'domains', type_='unique')
    op.alter_column('heartbeats', 'status',
               existing_type=postgresql.ENUM('up', 'down', 'degraded', 'pending', name='heartbeatstatus'),
               nullable=False)
    op.alter_column('heartbeats', 'checked_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.alter_column('hosting_packages', 'disk_space_gb',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('hosting_packages', 'bandwidth_gb',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('hosting_packages', 'domains_limit',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('hosting_packages', 'subdomains_limit',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('hosting_packages', 'databases_limit',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('hosting_packages', 'email_accounts_limit',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('hosting_packages', 'ftp_accounts_limit',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('hosting_packages', 'php_workers',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('hosting_packages', 'ram_mb',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('hosting_packages', 'cpu_cores',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('hosting_packages', 'monthly_price',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('hosting_packages', 'quarterly_price',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('hosting_packages', 'yearly_price',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('hosting_packages', 'biennial_price',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('hosting_packages', 'setup_fee',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('hosting_packages', 'currency',
               existing_type=sa.VARCHAR(length=3),
               nullable=False)
    op.alter_column('hosting_packages', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('hosting_packages', 'is_featured',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('hosting_packages', 'sort_order',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('hosting_packages', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('hosting_packages', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.drop_constraint(op.f('hosting_packages_slug_key'), 'hosting_packages', type_='unique')
    op.alter_column('incidents', 'status',
               existing_type=postgresql.ENUM('ongoing', 'resolved', 'investigating', name='incidentstatus'),
               nullable=False)
    op.alter_column('incidents', 'notification_sent',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('incidents', 'recovery_notification_sent',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('incidents', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.alter_column('incidents', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.alter_column('invoice_items', 'quantity',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('invoice_items', 'unit_price',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('invoice_items', 'total',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('invoices', 'status',
               existing_type=postgresql.ENUM('DRAFT', 'PENDING', 'PAID', 'OVERDUE', 'CANCELLED', 'REFUNDED', name='invoicestatus'),
               nullable=False)
    op.alter_column('invoices', 'subtotal',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('invoices', 'tax_rate',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('invoices', 'tax_amount',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('invoices', 'discount_amount',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('invoices', 'total',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('invoices', 'amount_paid',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('invoices', 'currency',
               existing_type=sa.VARCHAR(length=3),
               nullable=False)
    op.alter_column('invoices', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('invoices', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.drop_constraint(op.f('invoices_invoice_number_key'), 'invoices', type_='unique')
    op.alter_column('notification_channels', 'channel_type',
               existing_type=postgresql.ENUM('email', 'slack', 'telegram', 'webhook', 'discord', name='channeltype'),
               nullable=False)
    op.alter_column('notification_channels', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('notification_channels', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.alter_column('notification_channels', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.drop_index(op.f('ix_project_servers_project_id'), table_name='project_servers', if_exists=True)
    op.drop_index(op.f('ix_project_servers_server_id'), table_name='project_servers', if_exists=True)
    op.alter_column('projects', 'gdrive_connected',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('servers', 'panel_port',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('servers', 'panel_api_token',
               existing_type=sa.TEXT(),
               type_=forge.db.custom_types.EncryptedString(),
               existing_nullable=True)
    op.alter_column('servers', 'panel_verified',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('ssl_certificates', 'provider',
               existing_type=postgresql.ENUM('LETS_ENCRYPT', 'CLOUDFLARE', 'CYBERPANEL', 'COMODO', 'DIGICERT', 'GLOBALSIGN', 'SECTIGO', 'GODADDY', 'NAMECHEAP', 'OTHER', name='sslprovider'),
               nullable=False)
    op.alter_column('ssl_certificates', 'certificate_type',
               existing_type=postgresql.ENUM('DV', 'OV', 'EV', 'WILDCARD', 'MULTI_DOMAIN', name='certificatetype'),
               nullable=False)
    op.alter_column('ssl_certificates', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('ssl_certificates', 'auto_renew',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('ssl_certificates', 'is_wildcard',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('ssl_certificates', 'annual_cost',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('ssl_certificates', 'currency',
               existing_type=sa.VARCHAR(length=3),
               nullable=False)
    op.alter_column('ssl_certificates', 'renewal_failure_count',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('ssl_certificates', 'reminder_days',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('ssl_certificates', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('ssl_certificates', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.alter_column('subscriptions', 'billing_cycle',
               existing_type=postgresql.ENUM('MONTHLY', 'QUARTERLY', 'BIANNUAL', 'YEARLY', 'BIENNIAL', 'TRIENNIAL', name='billingcycle'),
               nullable=False)
    op.alter_column('subscriptions', 'currency',
               existing_type=sa.VARCHAR(length=3),
               nullable=False)
    op.alter_column('subscriptions', 'status',
               existing_type=postgresql.ENUM('ACTIVE', 'PENDING', 'CANCELLED', 'EXPIRED', 'SUSPENDED', name='subscriptionstatus'),
               nullable=False)
    op.alter_column('subscriptions', 'auto_renew',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('subscriptions', 'reminder_days',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('subscriptions', 'reminder_count',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('subscriptions', 'total_invoiced',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('subscriptions', 'total_paid',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('subscriptions', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('subscriptions', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.alter_column('ticket_messages', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.alter_column('ticket_messages', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.drop_index(op.f('ix_ticket_messages_ticket_id'), table_name='ticket_messages', if_exists=True)
    op.alter_column('tickets', 'status',
               existing_type=postgresql.ENUM('open', 'in_progress', 'waiting_reply', 'resolved', 'closed', name='ticketstatus'),
               nullable=False)
    op.alter_column('tickets', 'priority',
               existing_type=postgresql.ENUM('low', 'medium', 'high', 'urgent', name='ticketpriority'),
               nullable=False)
    op.alter_column('tickets', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.alter_column('tickets', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.drop_index(op.f('ix_tickets_client_id'), table_name='tickets', if_exists=True)
    op.drop_index(op.f('ix_tickets_status'), table_name='tickets', if_exists=True)
    op.add_column('wp_credentials', sa.Column('username_encrypted', sa.Text(), nullable=False))
    op.add_column('wp_credentials', sa.Column('username_salt', sa.String(length=100), nullable=False))
    op.add_column('wp_credentials', sa.Column('password_encrypted', sa.Text(), nullable=False))
    op.add_column('wp_credentials', sa.Column('password_salt', sa.String(length=100), nullable=False))
    
    # Create enum type
    credentialstatus = postgresql.ENUM('ACTIVE', 'INACTIVE', 'EXPIRED', name='credentialstatus')
    credentialstatus.create(op.get_bind())
    
    op.add_column('wp_credentials', sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', 'EXPIRED', name='credentialstatus'), nullable=False))
    op.drop_index(op.f('ix_wp_credentials_project_server_id'), table_name='wp_credentials', if_exists=True)
    op.drop_index(op.f('ix_wp_credentials_user_id'), table_name='wp_credentials', if_exists=True)
    op.drop_column('wp_credentials', 'is_active')
    op.drop_column('wp_credentials', 'wp_username_encrypted')
    op.drop_column('wp_credentials', 'wp_password_encrypted')
    op.alter_column('wp_site_states', 'plugins_count',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('wp_site_states', 'plugins_update_count',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('wp_site_states', 'themes_count',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('wp_site_states', 'themes_update_count',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('wp_site_states', 'users_count',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('wp_site_states', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.alter_column('wp_site_states', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.alter_column('wp_updates', 'status',
               existing_type=postgresql.ENUM('pending', 'applied', 'failed', 'rolled_back', 'skipped', name='updatestatus'),
               nullable=False)
    op.alter_column('wp_updates', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.alter_column('wp_updates', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.drop_index(op.f('ix_wp_updates_project_server_id'), table_name='wp_updates', if_exists=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    inspector = _get_inspector()
    op.create_index(op.f('ix_wp_updates_project_server_id'), 'wp_updates', ['project_server_id'], unique=False)
    op.alter_column('wp_updates', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.alter_column('wp_updates', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.alter_column('wp_updates', 'status',
               existing_type=postgresql.ENUM('pending', 'applied', 'failed', 'rolled_back', 'skipped', name='updatestatus'),
               nullable=True)
    op.alter_column('wp_site_states', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.alter_column('wp_site_states', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.alter_column('wp_site_states', 'users_count',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('wp_site_states', 'themes_update_count',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('wp_site_states', 'themes_count',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('wp_site_states', 'plugins_update_count',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('wp_site_states', 'plugins_count',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.add_column('wp_credentials', sa.Column('wp_password_encrypted', sa.TEXT(), autoincrement=False, nullable=False))
    op.add_column('wp_credentials', sa.Column('wp_username_encrypted', sa.TEXT(), autoincrement=False, nullable=False))
    op.add_column('wp_credentials', sa.Column('is_active', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False))
    op.create_index(op.f('ix_wp_credentials_user_id'), 'wp_credentials', ['user_id'], unique=False)
    op.create_index(op.f('ix_wp_credentials_project_server_id'), 'wp_credentials', ['project_server_id'], unique=False)
    op.drop_column('wp_credentials', 'status')
    op.drop_column('wp_credentials', 'password_salt')
    op.drop_column('wp_credentials', 'password_encrypted')
    op.drop_column('wp_credentials', 'username_salt')
    op.drop_column('wp_credentials', 'username_encrypted')
    op.create_index(op.f('ix_tickets_status'), 'tickets', ['status'], unique=False)
    op.create_index(op.f('ix_tickets_client_id'), 'tickets', ['client_id'], unique=False)
    op.alter_column('tickets', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.alter_column('tickets', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.alter_column('tickets', 'priority',
               existing_type=postgresql.ENUM('low', 'medium', 'high', 'urgent', name='ticketpriority'),
               nullable=True)
    op.alter_column('tickets', 'status',
               existing_type=postgresql.ENUM('open', 'in_progress', 'waiting_reply', 'resolved', 'closed', name='ticketstatus'),
               nullable=True)
    op.create_index(op.f('ix_ticket_messages_ticket_id'), 'ticket_messages', ['ticket_id'], unique=False)
    op.alter_column('ticket_messages', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.alter_column('ticket_messages', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.alter_column('subscriptions', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.alter_column('subscriptions', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('subscriptions', 'total_paid',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('subscriptions', 'total_invoiced',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('subscriptions', 'reminder_count',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('subscriptions', 'reminder_days',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('subscriptions', 'auto_renew',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('subscriptions', 'status',
               existing_type=postgresql.ENUM('ACTIVE', 'PENDING', 'CANCELLED', 'EXPIRED', 'SUSPENDED', name='subscriptionstatus'),
               nullable=True)
    op.alter_column('subscriptions', 'currency',
               existing_type=sa.VARCHAR(length=3),
               nullable=True)
    op.alter_column('subscriptions', 'billing_cycle',
               existing_type=postgresql.ENUM('MONTHLY', 'QUARTERLY', 'BIANNUAL', 'YEARLY', 'BIENNIAL', 'TRIENNIAL', name='billingcycle'),
               nullable=True)
    op.alter_column('ssl_certificates', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.alter_column('ssl_certificates', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('ssl_certificates', 'reminder_days',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('ssl_certificates', 'renewal_failure_count',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('ssl_certificates', 'currency',
               existing_type=sa.VARCHAR(length=3),
               nullable=True)
    op.alter_column('ssl_certificates', 'annual_cost',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('ssl_certificates', 'is_wildcard',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('ssl_certificates', 'auto_renew',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('ssl_certificates', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('ssl_certificates', 'certificate_type',
               existing_type=postgresql.ENUM('DV', 'OV', 'EV', 'WILDCARD', 'MULTI_DOMAIN', name='certificatetype'),
               nullable=True)
    op.alter_column('ssl_certificates', 'provider',
               existing_type=postgresql.ENUM('LETS_ENCRYPT', 'CLOUDFLARE', 'CYBERPANEL', 'COMODO', 'DIGICERT', 'GLOBALSIGN', 'SECTIGO', 'GODADDY', 'NAMECHEAP', 'OTHER', name='sslprovider'),
               nullable=True)
    op.alter_column('servers', 'panel_verified',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('servers', 'panel_api_token',
               existing_type=forge.db.custom_types.EncryptedString(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('servers', 'panel_port',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('projects', 'gdrive_connected',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.create_index(op.f('ix_project_servers_server_id'), 'project_servers', ['server_id'], unique=False)
    op.create_index(op.f('ix_project_servers_project_id'), 'project_servers', ['project_id'], unique=False)
    op.alter_column('notification_channels', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.alter_column('notification_channels', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.alter_column('notification_channels', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('notification_channels', 'channel_type',
               existing_type=postgresql.ENUM('email', 'slack', 'telegram', 'webhook', 'discord', name='channeltype'),
               nullable=True)
    op.create_unique_constraint(op.f('invoices_invoice_number_key'), 'invoices', ['invoice_number'], postgresql_nulls_not_distinct=False)
    op.alter_column('invoices', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.alter_column('invoices', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('invoices', 'currency',
               existing_type=sa.VARCHAR(length=3),
               nullable=True)
    op.alter_column('invoices', 'amount_paid',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('invoices', 'total',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('invoices', 'discount_amount',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('invoices', 'tax_amount',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('invoices', 'tax_rate',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('invoices', 'subtotal',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('invoices', 'status',
               existing_type=postgresql.ENUM('DRAFT', 'PENDING', 'PAID', 'OVERDUE', 'CANCELLED', 'REFUNDED', name='invoicestatus'),
               nullable=True)
    op.alter_column('invoice_items', 'total',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('invoice_items', 'unit_price',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('invoice_items', 'quantity',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('incidents', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.alter_column('incidents', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.alter_column('incidents', 'recovery_notification_sent',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('incidents', 'notification_sent',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('incidents', 'status',
               existing_type=postgresql.ENUM('ongoing', 'resolved', 'investigating', name='incidentstatus'),
               nullable=True)
    op.create_unique_constraint(op.f('hosting_packages_slug_key'), 'hosting_packages', ['slug'], postgresql_nulls_not_distinct=False)
    op.alter_column('hosting_packages', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.alter_column('hosting_packages', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('hosting_packages', 'sort_order',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('hosting_packages', 'is_featured',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('hosting_packages', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('hosting_packages', 'currency',
               existing_type=sa.VARCHAR(length=3),
               nullable=True)
    op.alter_column('hosting_packages', 'setup_fee',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('hosting_packages', 'biennial_price',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('hosting_packages', 'yearly_price',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('hosting_packages', 'quarterly_price',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('hosting_packages', 'monthly_price',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('hosting_packages', 'cpu_cores',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('hosting_packages', 'ram_mb',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('hosting_packages', 'php_workers',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('hosting_packages', 'ftp_accounts_limit',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('hosting_packages', 'email_accounts_limit',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('hosting_packages', 'databases_limit',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('hosting_packages', 'subdomains_limit',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('hosting_packages', 'domains_limit',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('hosting_packages', 'bandwidth_gb',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('hosting_packages', 'disk_space_gb',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('heartbeats', 'checked_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.alter_column('heartbeats', 'status',
               existing_type=postgresql.ENUM('up', 'down', 'degraded', 'pending', name='heartbeatstatus'),
               nullable=True)
    op.create_unique_constraint(op.f('domains_domain_name_key'), 'domains', ['domain_name'], postgresql_nulls_not_distinct=False)
    op.alter_column('domains', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.alter_column('domains', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('domains', 'reminder_days',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('domains', 'currency',
               existing_type=sa.VARCHAR(length=3),
               nullable=True)
    op.alter_column('domains', 'annual_cost',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('domains', 'transfer_lock',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('domains', 'privacy_protection',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('domains', 'auto_renew',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('domains', 'status',
               existing_type=postgresql.ENUM('ACTIVE', 'EXPIRED', 'PENDING_TRANSFER', 'LOCKED', 'REDEMPTION', 'PENDING_DELETE', name='domainstatus'),
               nullable=True)
    op.alter_column('domains', 'registrar',
               existing_type=postgresql.ENUM('NAMECHEAP', 'GODADDY', 'CLOUDFLARE', 'GOOGLE_DOMAINS', 'NAME_COM', 'PORKBUN', 'HOVER', 'DYNADOT', 'OTHER', name='registrar'),
               nullable=True)
    _add_columns_if_missing(
        inspector,
        'clients',
        [
            sa.Column('contract_terms', sa.TEXT(), autoincrement=False, nullable=True),
            sa.Column('monthly_retainer', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
            sa.Column('website', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
        ],
    )
    op.drop_constraint(None, 'clients', type_='foreignkey')
    clients_email_index = op.f('ix_clients_email')
    if _index_exists(inspector, 'clients', clients_email_index):
        op.drop_index(clients_email_index, table_name='clients')
        inspector = _get_inspector()
    if not _index_exists(inspector, 'clients', clients_email_index):
        op.create_index(clients_email_index, 'clients', ['email'], unique=True)
    op.create_unique_constraint(op.f('clients_email_key'), 'clients', ['email'], postgresql_nulls_not_distinct=False)
    op.alter_column('clients', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.alter_column('clients', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('clients', 'next_invoice_number',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('clients', 'invoice_prefix',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.alter_column('clients', 'auto_billing',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('clients', 'tax_rate',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('clients', 'currency',
               existing_type=sa.VARCHAR(length=3),
               nullable=True)
    op.alter_column('clients', 'payment_terms',
               existing_type=sa.String(length=50),
               type_=sa.INTEGER(),
               nullable=True)
    op.alter_column('clients', 'billing_status',
               existing_type=postgresql.ENUM('ACTIVE', 'INACTIVE', 'TRIAL', 'OVERDUE', name='billingstatus'),
               nullable=True)
    _drop_columns_if_exist(
        inspector,
        'clients',
        [
            'owner_id',
            'tags',
            'last_payment_date',
            'last_invoice_date',
            'outstanding_balance',
            'total_revenue',
            'monthly_rate',
            'country',
            'postal_code',
            'state',
            'city',
            'billing_name',
        ],
    )
    op.alter_column('client_users', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.alter_column('client_users', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.alter_column('client_users', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    audit_logs_index = op.f('ix_audit_logs_id')
    if _index_exists(inspector, 'audit_logs', audit_logs_index):
        op.drop_index(audit_logs_index, table_name='audit_logs')
    op.drop_table('audit_logs')
    # ### end Alembic commands ###
