"""Add ssh_private_key column

Revision ID: f2a35d04524a
Revises: 16cc5177cf8b
Create Date: 2026-01-13 13:16:49.546310

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import forge.db.custom_types


# revision identifiers, used by Alembic.
revision: str = 'f2a35d04524a'
down_revision: Union[str, Sequence[str], None] = '16cc5177cf8b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('servers', sa.Column('ssh_private_key', forge.db.custom_types.EncryptedString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('servers', 'ssh_private_key')
    # ### end Alembic commands ###
