"""add_panel_credentials

Revision ID: f85c2dde1d9b
Revises: f2a35d04524a
Create Date: 2026-01-13 15:20:42.089336

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f85c2dde1d9b'
down_revision: Union[str, Sequence[str], None] = 'f2a35d04524a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('client_users', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('client_users', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=False)
    op.alter_column('client_users', 'updated_at',
               existing_type=sa.DATETIME(),
               nullable=False)
    op.add_column('clients', sa.Column('billing_name', sa.String(length=255), nullable=True))
    op.add_column('clients', sa.Column('city', sa.String(length=100), nullable=True))
    op.add_column('clients', sa.Column('state', sa.String(length=100), nullable=True))
    op.add_column('clients', sa.Column('postal_code', sa.String(length=20), nullable=True))
    op.add_column('clients', sa.Column('country', sa.String(length=100), nullable=False))
    op.add_column('clients', sa.Column('monthly_rate', sa.Float(), nullable=False))
    op.add_column('clients', sa.Column('total_revenue', sa.Float(), nullable=False))
    op.add_column('clients', sa.Column('outstanding_balance', sa.Float(), nullable=False))
    op.add_column('clients', sa.Column('last_invoice_date', sa.Date(), nullable=True))
    op.add_column('clients', sa.Column('last_payment_date', sa.Date(), nullable=True))
    op.add_column('clients', sa.Column('tags', sa.Text(), nullable=True))
    op.add_column('clients', sa.Column('owner_id', sa.Integer(), nullable=False))
    op.alter_column('clients', 'billing_status',
               existing_type=sa.VARCHAR(length=8),
               type_=sa.Enum('ACTIVE', 'INACTIVE', 'TRIAL', 'OVERDUE', 'CANCELLED', name='billingstatus'),
               nullable=False)
    op.alter_column('clients', 'payment_terms',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=50),
               nullable=False)
    op.alter_column('clients', 'currency',
               existing_type=sa.VARCHAR(length=3),
               nullable=False)
    op.alter_column('clients', 'tax_rate',
               existing_type=sa.FLOAT(),
               nullable=False)
    op.alter_column('clients', 'auto_billing',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('clients', 'invoice_prefix',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.alter_column('clients', 'next_invoice_number',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('clients', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.alter_column('clients', 'updated_at',
               existing_type=sa.DATETIME(),
               nullable=False)
    op.drop_index(op.f('ix_clients_email'), table_name='clients')
    op.create_index(op.f('ix_clients_email'), 'clients', ['email'], unique=False)
    op.create_foreign_key(None, 'clients', 'users', ['owner_id'], ['id'])
    op.drop_column('clients', 'monthly_retainer')
    op.drop_column('clients', 'website')
    op.drop_column('clients', 'contract_terms')
    op.alter_column('domains', 'registrar',
               existing_type=sa.VARCHAR(length=14),
               nullable=False)
    op.alter_column('domains', 'status',
               existing_type=sa.VARCHAR(length=16),
               nullable=False)
    op.alter_column('domains', 'auto_renew',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('domains', 'privacy_protection',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('domains', 'transfer_lock',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('domains', 'annual_cost',
               existing_type=sa.FLOAT(),
               nullable=False)
    op.alter_column('domains', 'currency',
               existing_type=sa.VARCHAR(length=3),
               nullable=False)
    op.alter_column('domains', 'reminder_days',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('domains', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.alter_column('domains', 'updated_at',
               existing_type=sa.DATETIME(),
               nullable=False)
    op.alter_column('heartbeats', 'status',
               existing_type=sa.VARCHAR(length=8),
               nullable=False)
    op.alter_column('heartbeats', 'checked_at',
               existing_type=sa.DATETIME(),
               nullable=False)
    op.alter_column('hosting_packages', 'disk_space_gb',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('hosting_packages', 'bandwidth_gb',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('hosting_packages', 'domains_limit',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('hosting_packages', 'subdomains_limit',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('hosting_packages', 'databases_limit',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('hosting_packages', 'email_accounts_limit',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('hosting_packages', 'ftp_accounts_limit',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('hosting_packages', 'php_workers',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('hosting_packages', 'ram_mb',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('hosting_packages', 'cpu_cores',
               existing_type=sa.FLOAT(),
               nullable=False)
    op.alter_column('hosting_packages', 'monthly_price',
               existing_type=sa.FLOAT(),
               nullable=False)
    op.alter_column('hosting_packages', 'quarterly_price',
               existing_type=sa.FLOAT(),
               nullable=False)
    op.alter_column('hosting_packages', 'yearly_price',
               existing_type=sa.FLOAT(),
               nullable=False)
    op.alter_column('hosting_packages', 'biennial_price',
               existing_type=sa.FLOAT(),
               nullable=False)
    op.alter_column('hosting_packages', 'setup_fee',
               existing_type=sa.FLOAT(),
               nullable=False)
    op.alter_column('hosting_packages', 'currency',
               existing_type=sa.VARCHAR(length=3),
               nullable=False)
    op.alter_column('hosting_packages', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('hosting_packages', 'is_featured',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('hosting_packages', 'sort_order',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('hosting_packages', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.alter_column('hosting_packages', 'updated_at',
               existing_type=sa.DATETIME(),
               nullable=False)
    op.alter_column('incidents', 'status',
               existing_type=sa.VARCHAR(length=13),
               nullable=False)
    op.alter_column('incidents', 'notification_sent',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('incidents', 'recovery_notification_sent',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('incidents', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=False)
    op.alter_column('incidents', 'updated_at',
               existing_type=sa.DATETIME(),
               nullable=False)
    op.alter_column('invoice_items', 'quantity',
               existing_type=sa.FLOAT(),
               nullable=False)
    op.alter_column('invoice_items', 'unit_price',
               existing_type=sa.FLOAT(),
               nullable=False)
    op.alter_column('invoice_items', 'total',
               existing_type=sa.FLOAT(),
               nullable=False)
    op.alter_column('invoices', 'status',
               existing_type=sa.VARCHAR(length=9),
               nullable=False)
    op.alter_column('invoices', 'subtotal',
               existing_type=sa.FLOAT(),
               nullable=False)
    op.alter_column('invoices', 'tax_rate',
               existing_type=sa.FLOAT(),
               nullable=False)
    op.alter_column('invoices', 'tax_amount',
               existing_type=sa.FLOAT(),
               nullable=False)
    op.alter_column('invoices', 'discount_amount',
               existing_type=sa.FLOAT(),
               nullable=False)
    op.alter_column('invoices', 'total',
               existing_type=sa.FLOAT(),
               nullable=False)
    op.alter_column('invoices', 'amount_paid',
               existing_type=sa.FLOAT(),
               nullable=False)
    op.alter_column('invoices', 'currency',
               existing_type=sa.VARCHAR(length=3),
               nullable=False)
    op.alter_column('invoices', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.alter_column('invoices', 'updated_at',
               existing_type=sa.DATETIME(),
               nullable=False)
    op.alter_column('monitors', 'last_status',
               existing_type=sa.VARCHAR(length=8),
               type_=sa.Enum('up', 'down', 'degraded', 'pending', 'maintenance', name='monitorstatus'),
               existing_nullable=True)
    op.alter_column('notification_channels', 'channel_type',
               existing_type=sa.VARCHAR(length=8),
               nullable=False)
    op.alter_column('notification_channels', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('notification_channels', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=False)
    op.alter_column('notification_channels', 'updated_at',
               existing_type=sa.DATETIME(),
               nullable=False)
    op.drop_index(op.f('ix_project_servers_project_id'), table_name='project_servers')
    op.drop_index(op.f('ix_project_servers_server_id'), table_name='project_servers')
    op.alter_column('projects', 'gdrive_connected',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.add_column('servers', sa.Column('ssh_password', forge.db.custom_types.EncryptedString(), nullable=True))
    op.add_column('servers', sa.Column('ssh_private_key', forge.db.custom_types.EncryptedString(), nullable=True))
    op.add_column('servers', sa.Column('panel_username', forge.db.custom_types.EncryptedString(), nullable=True))
    op.add_column('servers', sa.Column('panel_password', forge.db.custom_types.EncryptedString(), nullable=True))
    op.alter_column('servers', 'panel_type',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.Enum('CYBERPANEL', 'CPANEL', 'PLESK', 'DIRECTADMIN', 'NONE', name='paneltype'),
               existing_nullable=False)
    op.alter_column('servers', 'panel_port',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('servers', 'panel_verified',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.drop_column('servers', 'panel_api_user')
    op.drop_column('servers', 'panel_api_token')
    op.alter_column('ssl_certificates', 'provider',
               existing_type=sa.VARCHAR(length=12),
               nullable=False)
    op.alter_column('ssl_certificates', 'certificate_type',
               existing_type=sa.VARCHAR(length=12),
               nullable=False)
    op.alter_column('ssl_certificates', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('ssl_certificates', 'auto_renew',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('ssl_certificates', 'is_wildcard',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('ssl_certificates', 'annual_cost',
               existing_type=sa.FLOAT(),
               nullable=False)
    op.alter_column('ssl_certificates', 'currency',
               existing_type=sa.VARCHAR(length=3),
               nullable=False)
    op.alter_column('ssl_certificates', 'renewal_failure_count',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('ssl_certificates', 'reminder_days',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('ssl_certificates', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.alter_column('ssl_certificates', 'updated_at',
               existing_type=sa.DATETIME(),
               nullable=False)
    op.alter_column('subscriptions', 'billing_cycle',
               existing_type=sa.VARCHAR(length=9),
               nullable=False)
    op.alter_column('subscriptions', 'currency',
               existing_type=sa.VARCHAR(length=3),
               nullable=False)
    op.alter_column('subscriptions', 'status',
               existing_type=sa.VARCHAR(length=9),
               nullable=False)
    op.alter_column('subscriptions', 'auto_renew',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('subscriptions', 'reminder_days',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('subscriptions', 'reminder_count',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('subscriptions', 'total_invoiced',
               existing_type=sa.FLOAT(),
               nullable=False)
    op.alter_column('subscriptions', 'total_paid',
               existing_type=sa.FLOAT(),
               nullable=False)
    op.alter_column('subscriptions', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.alter_column('subscriptions', 'updated_at',
               existing_type=sa.DATETIME(),
               nullable=False)
    op.alter_column('ticket_messages', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=False)
    op.alter_column('ticket_messages', 'updated_at',
               existing_type=sa.DATETIME(),
               nullable=False)
    op.drop_index(op.f('ix_ticket_messages_ticket_id'), table_name='ticket_messages')
    op.alter_column('tickets', 'status',
               existing_type=sa.VARCHAR(length=13),
               nullable=False)
    op.alter_column('tickets', 'priority',
               existing_type=sa.VARCHAR(length=6),
               nullable=False)
    op.alter_column('tickets', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=False)
    op.alter_column('tickets', 'updated_at',
               existing_type=sa.DATETIME(),
               nullable=False)
    op.drop_index(op.f('ix_tickets_client_id'), table_name='tickets')
    op.drop_index(op.f('ix_tickets_status'), table_name='tickets')
    op.add_column('users', sa.Column('avatar_url', sa.String(length=500), nullable=True))
    op.add_column('wp_credentials', sa.Column('username_encrypted', sa.Text(), nullable=False))
    op.add_column('wp_credentials', sa.Column('username_salt', sa.String(length=100), nullable=False))
    op.add_column('wp_credentials', sa.Column('password_encrypted', sa.Text(), nullable=False))
    op.add_column('wp_credentials', sa.Column('password_salt', sa.String(length=100), nullable=False))
    op.add_column('wp_credentials', sa.Column('status', sa.Enum('active', 'inactive', 'expired', name='credentialstatus'), nullable=False))
    op.drop_index(op.f('ix_wp_credentials_project_server_id'), table_name='wp_credentials')
    op.drop_index(op.f('ix_wp_credentials_user_id'), table_name='wp_credentials')
    op.drop_column('wp_credentials', 'wp_username_encrypted')
    op.drop_column('wp_credentials', 'wp_password_encrypted')
    op.drop_column('wp_credentials', 'is_active')
    op.alter_column('wp_site_states', 'plugins_count',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('wp_site_states', 'plugins_update_count',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('wp_site_states', 'themes_count',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('wp_site_states', 'themes_update_count',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('wp_site_states', 'users_count',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('wp_site_states', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=False)
    op.alter_column('wp_site_states', 'updated_at',
               existing_type=sa.DATETIME(),
               nullable=False)
    op.alter_column('wp_updates', 'status',
               existing_type=sa.VARCHAR(length=11),
               nullable=False)
    op.alter_column('wp_updates', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=False)
    op.alter_column('wp_updates', 'updated_at',
               existing_type=sa.DATETIME(),
               nullable=False)
    op.drop_index(op.f('ix_wp_updates_project_server_id'), table_name='wp_updates')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_wp_updates_project_server_id'), 'wp_updates', ['project_server_id'], unique=False)
    op.alter_column('wp_updates', 'updated_at',
               existing_type=sa.DATETIME(),
               nullable=True)
    op.alter_column('wp_updates', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=True)
    op.alter_column('wp_updates', 'status',
               existing_type=sa.VARCHAR(length=11),
               nullable=True)
    op.alter_column('wp_site_states', 'updated_at',
               existing_type=sa.DATETIME(),
               nullable=True)
    op.alter_column('wp_site_states', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=True)
    op.alter_column('wp_site_states', 'users_count',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('wp_site_states', 'themes_update_count',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('wp_site_states', 'themes_count',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('wp_site_states', 'plugins_update_count',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('wp_site_states', 'plugins_count',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.add_column('wp_credentials', sa.Column('is_active', sa.BOOLEAN(), server_default=sa.text("'true'"), nullable=False))
    op.add_column('wp_credentials', sa.Column('wp_password_encrypted', sa.TEXT(), nullable=False))
    op.add_column('wp_credentials', sa.Column('wp_username_encrypted', sa.TEXT(), nullable=False))
    op.create_index(op.f('ix_wp_credentials_user_id'), 'wp_credentials', ['user_id'], unique=False)
    op.create_index(op.f('ix_wp_credentials_project_server_id'), 'wp_credentials', ['project_server_id'], unique=False)
    op.drop_column('wp_credentials', 'status')
    op.drop_column('wp_credentials', 'password_salt')
    op.drop_column('wp_credentials', 'password_encrypted')
    op.drop_column('wp_credentials', 'username_salt')
    op.drop_column('wp_credentials', 'username_encrypted')
    op.drop_column('users', 'avatar_url')
    op.create_index(op.f('ix_tickets_status'), 'tickets', ['status'], unique=False)
    op.create_index(op.f('ix_tickets_client_id'), 'tickets', ['client_id'], unique=False)
    op.alter_column('tickets', 'updated_at',
               existing_type=sa.DATETIME(),
               nullable=True)
    op.alter_column('tickets', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=True)
    op.alter_column('tickets', 'priority',
               existing_type=sa.VARCHAR(length=6),
               nullable=True)
    op.alter_column('tickets', 'status',
               existing_type=sa.VARCHAR(length=13),
               nullable=True)
    op.create_index(op.f('ix_ticket_messages_ticket_id'), 'ticket_messages', ['ticket_id'], unique=False)
    op.alter_column('ticket_messages', 'updated_at',
               existing_type=sa.DATETIME(),
               nullable=True)
    op.alter_column('ticket_messages', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=True)
    op.alter_column('subscriptions', 'updated_at',
               existing_type=sa.DATETIME(),
               nullable=True)
    op.alter_column('subscriptions', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.alter_column('subscriptions', 'total_paid',
               existing_type=sa.FLOAT(),
               nullable=True)
    op.alter_column('subscriptions', 'total_invoiced',
               existing_type=sa.FLOAT(),
               nullable=True)
    op.alter_column('subscriptions', 'reminder_count',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('subscriptions', 'reminder_days',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('subscriptions', 'auto_renew',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('subscriptions', 'status',
               existing_type=sa.VARCHAR(length=9),
               nullable=True)
    op.alter_column('subscriptions', 'currency',
               existing_type=sa.VARCHAR(length=3),
               nullable=True)
    op.alter_column('subscriptions', 'billing_cycle',
               existing_type=sa.VARCHAR(length=9),
               nullable=True)
    op.alter_column('ssl_certificates', 'updated_at',
               existing_type=sa.DATETIME(),
               nullable=True)
    op.alter_column('ssl_certificates', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.alter_column('ssl_certificates', 'reminder_days',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('ssl_certificates', 'renewal_failure_count',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('ssl_certificates', 'currency',
               existing_type=sa.VARCHAR(length=3),
               nullable=True)
    op.alter_column('ssl_certificates', 'annual_cost',
               existing_type=sa.FLOAT(),
               nullable=True)
    op.alter_column('ssl_certificates', 'is_wildcard',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('ssl_certificates', 'auto_renew',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('ssl_certificates', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('ssl_certificates', 'certificate_type',
               existing_type=sa.VARCHAR(length=12),
               nullable=True)
    op.alter_column('ssl_certificates', 'provider',
               existing_type=sa.VARCHAR(length=12),
               nullable=True)
    op.add_column('servers', sa.Column('panel_api_token', sa.TEXT(), nullable=True))
    op.add_column('servers', sa.Column('panel_api_user', sa.VARCHAR(length=100), nullable=True))
    op.alter_column('servers', 'panel_verified',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('servers', 'panel_port',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('servers', 'panel_type',
               existing_type=sa.Enum('CYBERPANEL', 'CPANEL', 'PLESK', 'DIRECTADMIN', 'NONE', name='paneltype'),
               type_=sa.VARCHAR(length=10),
               existing_nullable=False)
    op.drop_column('servers', 'panel_password')
    op.drop_column('servers', 'panel_username')
    op.drop_column('servers', 'ssh_private_key')
    op.drop_column('servers', 'ssh_password')
    op.alter_column('projects', 'gdrive_connected',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.create_index(op.f('ix_project_servers_server_id'), 'project_servers', ['server_id'], unique=False)
    op.create_index(op.f('ix_project_servers_project_id'), 'project_servers', ['project_id'], unique=False)
    op.alter_column('notification_channels', 'updated_at',
               existing_type=sa.DATETIME(),
               nullable=True)
    op.alter_column('notification_channels', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=True)
    op.alter_column('notification_channels', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('notification_channels', 'channel_type',
               existing_type=sa.VARCHAR(length=8),
               nullable=True)
    op.alter_column('monitors', 'last_status',
               existing_type=sa.Enum('up', 'down', 'degraded', 'pending', 'maintenance', name='monitorstatus'),
               type_=sa.VARCHAR(length=8),
               existing_nullable=True)
    op.alter_column('invoices', 'updated_at',
               existing_type=sa.DATETIME(),
               nullable=True)
    op.alter_column('invoices', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.alter_column('invoices', 'currency',
               existing_type=sa.VARCHAR(length=3),
               nullable=True)
    op.alter_column('invoices', 'amount_paid',
               existing_type=sa.FLOAT(),
               nullable=True)
    op.alter_column('invoices', 'total',
               existing_type=sa.FLOAT(),
               nullable=True)
    op.alter_column('invoices', 'discount_amount',
               existing_type=sa.FLOAT(),
               nullable=True)
    op.alter_column('invoices', 'tax_amount',
               existing_type=sa.FLOAT(),
               nullable=True)
    op.alter_column('invoices', 'tax_rate',
               existing_type=sa.FLOAT(),
               nullable=True)
    op.alter_column('invoices', 'subtotal',
               existing_type=sa.FLOAT(),
               nullable=True)
    op.alter_column('invoices', 'status',
               existing_type=sa.VARCHAR(length=9),
               nullable=True)
    op.alter_column('invoice_items', 'total',
               existing_type=sa.FLOAT(),
               nullable=True)
    op.alter_column('invoice_items', 'unit_price',
               existing_type=sa.FLOAT(),
               nullable=True)
    op.alter_column('invoice_items', 'quantity',
               existing_type=sa.FLOAT(),
               nullable=True)
    op.alter_column('incidents', 'updated_at',
               existing_type=sa.DATETIME(),
               nullable=True)
    op.alter_column('incidents', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=True)
    op.alter_column('incidents', 'recovery_notification_sent',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('incidents', 'notification_sent',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('incidents', 'status',
               existing_type=sa.VARCHAR(length=13),
               nullable=True)
    op.alter_column('hosting_packages', 'updated_at',
               existing_type=sa.DATETIME(),
               nullable=True)
    op.alter_column('hosting_packages', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.alter_column('hosting_packages', 'sort_order',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('hosting_packages', 'is_featured',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('hosting_packages', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('hosting_packages', 'currency',
               existing_type=sa.VARCHAR(length=3),
               nullable=True)
    op.alter_column('hosting_packages', 'setup_fee',
               existing_type=sa.FLOAT(),
               nullable=True)
    op.alter_column('hosting_packages', 'biennial_price',
               existing_type=sa.FLOAT(),
               nullable=True)
    op.alter_column('hosting_packages', 'yearly_price',
               existing_type=sa.FLOAT(),
               nullable=True)
    op.alter_column('hosting_packages', 'quarterly_price',
               existing_type=sa.FLOAT(),
               nullable=True)
    op.alter_column('hosting_packages', 'monthly_price',
               existing_type=sa.FLOAT(),
               nullable=True)
    op.alter_column('hosting_packages', 'cpu_cores',
               existing_type=sa.FLOAT(),
               nullable=True)
    op.alter_column('hosting_packages', 'ram_mb',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('hosting_packages', 'php_workers',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('hosting_packages', 'ftp_accounts_limit',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('hosting_packages', 'email_accounts_limit',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('hosting_packages', 'databases_limit',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('hosting_packages', 'subdomains_limit',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('hosting_packages', 'domains_limit',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('hosting_packages', 'bandwidth_gb',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('hosting_packages', 'disk_space_gb',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('heartbeats', 'checked_at',
               existing_type=sa.DATETIME(),
               nullable=True)
    op.alter_column('heartbeats', 'status',
               existing_type=sa.VARCHAR(length=8),
               nullable=True)
    op.alter_column('domains', 'updated_at',
               existing_type=sa.DATETIME(),
               nullable=True)
    op.alter_column('domains', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.alter_column('domains', 'reminder_days',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('domains', 'currency',
               existing_type=sa.VARCHAR(length=3),
               nullable=True)
    op.alter_column('domains', 'annual_cost',
               existing_type=sa.FLOAT(),
               nullable=True)
    op.alter_column('domains', 'transfer_lock',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('domains', 'privacy_protection',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('domains', 'auto_renew',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('domains', 'status',
               existing_type=sa.VARCHAR(length=16),
               nullable=True)
    op.alter_column('domains', 'registrar',
               existing_type=sa.VARCHAR(length=14),
               nullable=True)
    op.add_column('clients', sa.Column('contract_terms', sa.TEXT(), nullable=True))
    op.add_column('clients', sa.Column('website', sa.VARCHAR(length=500), nullable=True))
    op.add_column('clients', sa.Column('monthly_retainer', sa.FLOAT(), nullable=True))
    op.drop_constraint(None, 'clients', type_='foreignkey')
    op.drop_index(op.f('ix_clients_email'), table_name='clients')
    op.create_index(op.f('ix_clients_email'), 'clients', ['email'], unique=1)
    op.alter_column('clients', 'updated_at',
               existing_type=sa.DATETIME(),
               nullable=True)
    op.alter_column('clients', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.alter_column('clients', 'next_invoice_number',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('clients', 'invoice_prefix',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.alter_column('clients', 'auto_billing',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('clients', 'tax_rate',
               existing_type=sa.FLOAT(),
               nullable=True)
    op.alter_column('clients', 'currency',
               existing_type=sa.VARCHAR(length=3),
               nullable=True)
    op.alter_column('clients', 'payment_terms',
               existing_type=sa.String(length=50),
               type_=sa.INTEGER(),
               nullable=True)
    op.alter_column('clients', 'billing_status',
               existing_type=sa.Enum('ACTIVE', 'INACTIVE', 'TRIAL', 'OVERDUE', 'CANCELLED', name='billingstatus'),
               type_=sa.VARCHAR(length=8),
               nullable=True)
    op.drop_column('clients', 'owner_id')
    op.drop_column('clients', 'tags')
    op.drop_column('clients', 'last_payment_date')
    op.drop_column('clients', 'last_invoice_date')
    op.drop_column('clients', 'outstanding_balance')
    op.drop_column('clients', 'total_revenue')
    op.drop_column('clients', 'monthly_rate')
    op.drop_column('clients', 'country')
    op.drop_column('clients', 'postal_code')
    op.drop_column('clients', 'state')
    op.drop_column('clients', 'city')
    op.drop_column('clients', 'billing_name')
    op.alter_column('client_users', 'updated_at',
               existing_type=sa.DATETIME(),
               nullable=True)
    op.alter_column('client_users', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=True)
    op.alter_column('client_users', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    # ### end Alembic commands ###
