"""add_panel_credentials

Revision ID: f85c2dde1d9b
Revises: f2a35d04524a
Create Date: 2026-01-13 15:20:42.089336

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import forge.db.custom_types


# revision identifiers, used by Alembic.
revision: str = 'f85c2dde1d9b'
down_revision: Union[str, Sequence[str], None] = 'f2a35d04524a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def _get_inspector() -> sa.Inspector:
    return sa.inspect(op.get_bind())


def _table_exists(inspector: sa.Inspector, table_name: str) -> bool:
    return table_name in inspector.get_table_names()


def _column_exists(inspector: sa.Inspector, table_name: str, column_name: str) -> bool:
    if not _table_exists(inspector, table_name):
        return False
    return any(column["name"] == column_name for column in inspector.get_columns(table_name))


def _index_exists(inspector: sa.Inspector, table_name: str, index_name: str) -> bool:
    if not _table_exists(inspector, table_name):
        return False
    return any(index["name"] == index_name for index in inspector.get_indexes(table_name))


def _add_columns_if_missing(
    inspector: sa.Inspector,
    table_name: str,
    columns: Sequence[sa.Column],
) -> None:
    for column in columns:
        if not _column_exists(inspector, table_name, column.name):
            op.add_column(table_name, column)


def _drop_columns_if_exist(
    inspector: sa.Inspector,
    table_name: str,
    column_names: Sequence[str],
) -> None:
    for column_name in column_names:
        if _column_exists(inspector, table_name, column_name):
            op.drop_column(table_name, column_name)


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    inspector = _get_inspector()
    op.alter_column('client_users', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('client_users', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=False)
    op.alter_column('client_users', 'updated_at',
               existing_type=sa.DATETIME(),
               nullable=False)
    # Client columns already added in 8dece49dbc7f
    op.alter_column('clients', 'billing_status',
               existing_type=sa.VARCHAR(length=8),
               type_=sa.Enum('ACTIVE', 'INACTIVE', 'TRIAL', 'OVERDUE', 'CANCELLED', name='billingstatus'),
               nullable=False)
    op.alter_column('clients', 'payment_terms',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=50),
               nullable=False)
    op.alter_column('clients', 'currency',
               existing_type=sa.VARCHAR(length=3),
               nullable=False)
    op.alter_column('clients', 'tax_rate',
               existing_type=sa.FLOAT(),
               nullable=False)
    op.alter_column('clients', 'auto_billing',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('clients', 'invoice_prefix',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.alter_column('clients', 'next_invoice_number',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('clients', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.alter_column('clients', 'updated_at',
               existing_type=sa.DATETIME(),
               nullable=False)
    clients_email_index = op.f('ix_clients_email')
    if _index_exists(inspector, 'clients', clients_email_index):
        op.drop_index(clients_email_index, table_name='clients')
    op.create_index(op.f('ix_clients_email'), 'clients', ['email'], unique=False)
    op.create_foreign_key(None, 'clients', 'users', ['owner_id'], ['id'])
    _drop_columns_if_exist(inspector, 'clients', ['monthly_retainer', 'website', 'contract_terms'])
    op.alter_column('domains', 'registrar',
               existing_type=sa.VARCHAR(length=14),
               nullable=False)
    op.alter_column('domains', 'status',
               existing_type=sa.VARCHAR(length=16),
               nullable=False)
    op.alter_column('domains', 'auto_renew',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('domains', 'privacy_protection',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('domains', 'transfer_lock',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('domains', 'annual_cost',
               existing_type=sa.FLOAT(),
               nullable=False)
    op.alter_column('domains', 'currency',
               existing_type=sa.VARCHAR(length=3),
               nullable=False)
    op.alter_column('domains', 'reminder_days',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('domains', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.alter_column('domains', 'updated_at',
               existing_type=sa.DATETIME(),
               nullable=False)
    op.alter_column('heartbeats', 'status',
               existing_type=sa.VARCHAR(length=8),
               nullable=False)
    op.alter_column('heartbeats', 'checked_at',
               existing_type=sa.DATETIME(),
               nullable=False)
    op.alter_column('hosting_packages', 'disk_space_gb',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('hosting_packages', 'bandwidth_gb',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('hosting_packages', 'domains_limit',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('hosting_packages', 'subdomains_limit',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('hosting_packages', 'databases_limit',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('hosting_packages', 'email_accounts_limit',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('hosting_packages', 'ftp_accounts_limit',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('hosting_packages', 'php_workers',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('hosting_packages', 'ram_mb',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('hosting_packages', 'cpu_cores',
               existing_type=sa.FLOAT(),
               nullable=False)
    op.alter_column('hosting_packages', 'monthly_price',
               existing_type=sa.FLOAT(),
               nullable=False)
    op.alter_column('hosting_packages', 'quarterly_price',
               existing_type=sa.FLOAT(),
               nullable=False)
    op.alter_column('hosting_packages', 'yearly_price',
               existing_type=sa.FLOAT(),
               nullable=False)
    op.alter_column('hosting_packages', 'biennial_price',
               existing_type=sa.FLOAT(),
               nullable=False)
    op.alter_column('hosting_packages', 'setup_fee',
               existing_type=sa.FLOAT(),
               nullable=False)
    op.alter_column('hosting_packages', 'currency',
               existing_type=sa.VARCHAR(length=3),
               nullable=False)
    op.alter_column('hosting_packages', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('hosting_packages', 'is_featured',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('hosting_packages', 'sort_order',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('hosting_packages', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.alter_column('hosting_packages', 'updated_at',
               existing_type=sa.DATETIME(),
               nullable=False)
    op.alter_column('incidents', 'status',
               existing_type=sa.VARCHAR(length=13),
               nullable=False)
    op.alter_column('incidents', 'notification_sent',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('incidents', 'recovery_notification_sent',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('incidents', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=False)
    op.alter_column('incidents', 'updated_at',
               existing_type=sa.DATETIME(),
               nullable=False)
    op.alter_column('invoice_items', 'quantity',
               existing_type=sa.FLOAT(),
               nullable=False)
    op.alter_column('invoice_items', 'unit_price',
               existing_type=sa.FLOAT(),
               nullable=False)
    op.alter_column('invoice_items', 'total',
               existing_type=sa.FLOAT(),
               nullable=False)
    op.alter_column('invoices', 'status',
               existing_type=sa.VARCHAR(length=9),
               nullable=False)
    op.alter_column('invoices', 'subtotal',
               existing_type=sa.FLOAT(),
               nullable=False)
    op.alter_column('invoices', 'tax_rate',
               existing_type=sa.FLOAT(),
               nullable=False)
    op.alter_column('invoices', 'tax_amount',
               existing_type=sa.FLOAT(),
               nullable=False)
    op.alter_column('invoices', 'discount_amount',
               existing_type=sa.FLOAT(),
               nullable=False)
    op.alter_column('invoices', 'total',
               existing_type=sa.FLOAT(),
               nullable=False)
    op.alter_column('invoices', 'amount_paid',
               existing_type=sa.FLOAT(),
               nullable=False)
    op.alter_column('invoices', 'currency',
               existing_type=sa.VARCHAR(length=3),
               nullable=False)
    op.alter_column('invoices', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.alter_column('invoices', 'updated_at',
               existing_type=sa.DATETIME(),
               nullable=False)
    op.alter_column('monitors', 'last_status',
               existing_type=sa.VARCHAR(length=8),
               type_=sa.Enum('up', 'down', 'degraded', 'pending', 'maintenance', name='monitorstatus'),
               existing_nullable=True)
    op.alter_column('notification_channels', 'channel_type',
               existing_type=sa.VARCHAR(length=8),
               nullable=False)
    op.alter_column('notification_channels', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('notification_channels', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=False)
    op.alter_column('notification_channels', 'updated_at',
               existing_type=sa.DATETIME(),
               nullable=False)
    project_servers_project_index = op.f('ix_project_servers_project_id')
    if _index_exists(inspector, 'project_servers', project_servers_project_index):
        op.drop_index(project_servers_project_index, table_name='project_servers')
    project_servers_server_index = op.f('ix_project_servers_server_id')
    if _index_exists(inspector, 'project_servers', project_servers_server_index):
        op.drop_index(project_servers_server_index, table_name='project_servers')
    op.alter_column('projects', 'gdrive_connected',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    _add_columns_if_missing(
        inspector,
        'servers',
        [
            sa.Column('ssh_password', forge.db.custom_types.EncryptedString(), nullable=True),
            sa.Column('ssh_private_key', forge.db.custom_types.EncryptedString(), nullable=True),
            sa.Column('panel_username', forge.db.custom_types.EncryptedString(), nullable=True),
            sa.Column('panel_password', forge.db.custom_types.EncryptedString(), nullable=True),
        ],
    )
    op.alter_column('servers', 'panel_type',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.Enum('CYBERPANEL', 'CPANEL', 'PLESK', 'DIRECTADMIN', 'NONE', name='paneltype'),
               existing_nullable=False)
    op.alter_column('servers', 'panel_port',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('servers', 'panel_verified',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    _drop_columns_if_exist(inspector, 'servers', ['panel_api_user', 'panel_api_token'])
    op.alter_column('ssl_certificates', 'provider',
               existing_type=sa.VARCHAR(length=12),
               nullable=False)
    op.alter_column('ssl_certificates', 'certificate_type',
               existing_type=sa.VARCHAR(length=12),
               nullable=False)
    op.alter_column('ssl_certificates', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('ssl_certificates', 'auto_renew',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('ssl_certificates', 'is_wildcard',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('ssl_certificates', 'annual_cost',
               existing_type=sa.FLOAT(),
               nullable=False)
    op.alter_column('ssl_certificates', 'currency',
               existing_type=sa.VARCHAR(length=3),
               nullable=False)
    op.alter_column('ssl_certificates', 'renewal_failure_count',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('ssl_certificates', 'reminder_days',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('ssl_certificates', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.alter_column('ssl_certificates', 'updated_at',
               existing_type=sa.DATETIME(),
               nullable=False)
    op.alter_column('subscriptions', 'billing_cycle',
               existing_type=sa.VARCHAR(length=9),
               nullable=False)
    op.alter_column('subscriptions', 'currency',
               existing_type=sa.VARCHAR(length=3),
               nullable=False)
    op.alter_column('subscriptions', 'status',
               existing_type=sa.VARCHAR(length=9),
               nullable=False)
    op.alter_column('subscriptions', 'auto_renew',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('subscriptions', 'reminder_days',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('subscriptions', 'reminder_count',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('subscriptions', 'total_invoiced',
               existing_type=sa.FLOAT(),
               nullable=False)
    op.alter_column('subscriptions', 'total_paid',
               existing_type=sa.FLOAT(),
               nullable=False)
    op.alter_column('subscriptions', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.alter_column('subscriptions', 'updated_at',
               existing_type=sa.DATETIME(),
               nullable=False)
    op.alter_column('ticket_messages', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=False)
    op.alter_column('ticket_messages', 'updated_at',
               existing_type=sa.DATETIME(),
               nullable=False)
    ticket_messages_ticket_index = op.f('ix_ticket_messages_ticket_id')
    if _index_exists(inspector, 'ticket_messages', ticket_messages_ticket_index):
        op.drop_index(ticket_messages_ticket_index, table_name='ticket_messages')
    op.alter_column('tickets', 'status',
               existing_type=sa.VARCHAR(length=13),
               nullable=False)
    op.alter_column('tickets', 'priority',
               existing_type=sa.VARCHAR(length=6),
               nullable=False)
    op.alter_column('tickets', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=False)
    op.alter_column('tickets', 'updated_at',
               existing_type=sa.DATETIME(),
               nullable=False)
    tickets_client_index = op.f('ix_tickets_client_id')
    if _index_exists(inspector, 'tickets', tickets_client_index):
        op.drop_index(tickets_client_index, table_name='tickets')
    tickets_status_index = op.f('ix_tickets_status')
    if _index_exists(inspector, 'tickets', tickets_status_index):
        op.drop_index(tickets_status_index, table_name='tickets')
    _add_columns_if_missing(
        inspector,
        'users',
        [sa.Column('avatar_url', sa.String(length=500), nullable=True)],
    )
    credential_status_enum = sa.Enum(
        'active', 'inactive', 'expired', name='credentialstatus'
    )
    credential_status_enum.create(op.get_bind(), checkfirst=True)
    _add_columns_if_missing(
        inspector,
        'wp_credentials',
        [
            sa.Column('username_encrypted', sa.Text(), nullable=False),
            sa.Column('username_salt', sa.String(length=100), nullable=False),
            sa.Column('password_encrypted', sa.Text(), nullable=False),
            sa.Column('password_salt', sa.String(length=100), nullable=False),
            sa.Column('status', credential_status_enum, nullable=False),
        ],
    )
    wp_credentials_project_index = op.f('ix_wp_credentials_project_server_id')
    if _index_exists(inspector, 'wp_credentials', wp_credentials_project_index):
        op.drop_index(wp_credentials_project_index, table_name='wp_credentials')
    wp_credentials_user_index = op.f('ix_wp_credentials_user_id')
    if _index_exists(inspector, 'wp_credentials', wp_credentials_user_index):
        op.drop_index(wp_credentials_user_index, table_name='wp_credentials')
    _drop_columns_if_exist(
        inspector,
        'wp_credentials',
        ['wp_username_encrypted', 'wp_password_encrypted', 'is_active'],
    )
    op.alter_column('wp_site_states', 'plugins_count',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('wp_site_states', 'plugins_update_count',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('wp_site_states', 'themes_count',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('wp_site_states', 'themes_update_count',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('wp_site_states', 'users_count',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('wp_site_states', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=False)
    op.alter_column('wp_site_states', 'updated_at',
               existing_type=sa.DATETIME(),
               nullable=False)
    op.alter_column('wp_updates', 'status',
               existing_type=sa.VARCHAR(length=11),
               nullable=False)
    op.alter_column('wp_updates', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=False)
    op.alter_column('wp_updates', 'updated_at',
               existing_type=sa.DATETIME(),
               nullable=False)
    wp_updates_project_index = op.f('ix_wp_updates_project_server_id')
    if _index_exists(inspector, 'wp_updates', wp_updates_project_index):
        op.drop_index(wp_updates_project_index, table_name='wp_updates')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    inspector = _get_inspector()
    op.create_index(op.f('ix_wp_updates_project_server_id'), 'wp_updates', ['project_server_id'], unique=False)
    op.alter_column('wp_updates', 'updated_at',
               existing_type=sa.DATETIME(),
               nullable=True)
    op.alter_column('wp_updates', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=True)
    op.alter_column('wp_updates', 'status',
               existing_type=sa.VARCHAR(length=11),
               nullable=True)
    op.alter_column('wp_site_states', 'updated_at',
               existing_type=sa.DATETIME(),
               nullable=True)
    op.alter_column('wp_site_states', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=True)
    op.alter_column('wp_site_states', 'users_count',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('wp_site_states', 'themes_update_count',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('wp_site_states', 'themes_count',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('wp_site_states', 'plugins_update_count',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('wp_site_states', 'plugins_count',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.add_column('wp_credentials', sa.Column('is_active', sa.BOOLEAN(), server_default=sa.text("'true'"), nullable=False))
    op.add_column('wp_credentials', sa.Column('wp_password_encrypted', sa.TEXT(), nullable=False))
    op.add_column('wp_credentials', sa.Column('wp_username_encrypted', sa.TEXT(), nullable=False))
    op.create_index(op.f('ix_wp_credentials_user_id'), 'wp_credentials', ['user_id'], unique=False)
    op.create_index(op.f('ix_wp_credentials_project_server_id'), 'wp_credentials', ['project_server_id'], unique=False)
    op.drop_column('wp_credentials', 'status')
    op.drop_column('wp_credentials', 'password_salt')
    op.drop_column('wp_credentials', 'password_encrypted')
    op.drop_column('wp_credentials', 'username_salt')
    op.drop_column('wp_credentials', 'username_encrypted')
    op.drop_column('users', 'avatar_url')
    op.create_index(op.f('ix_tickets_status'), 'tickets', ['status'], unique=False)
    op.create_index(op.f('ix_tickets_client_id'), 'tickets', ['client_id'], unique=False)
    op.alter_column('tickets', 'updated_at',
               existing_type=sa.DATETIME(),
               nullable=True)
    op.alter_column('tickets', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=True)
    op.alter_column('tickets', 'priority',
               existing_type=sa.VARCHAR(length=6),
               nullable=True)
    op.alter_column('tickets', 'status',
               existing_type=sa.VARCHAR(length=13),
               nullable=True)
    op.create_index(op.f('ix_ticket_messages_ticket_id'), 'ticket_messages', ['ticket_id'], unique=False)
    op.alter_column('ticket_messages', 'updated_at',
               existing_type=sa.DATETIME(),
               nullable=True)
    op.alter_column('ticket_messages', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=True)
    op.alter_column('subscriptions', 'updated_at',
               existing_type=sa.DATETIME(),
               nullable=True)
    op.alter_column('subscriptions', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.alter_column('subscriptions', 'total_paid',
               existing_type=sa.FLOAT(),
               nullable=True)
    op.alter_column('subscriptions', 'total_invoiced',
               existing_type=sa.FLOAT(),
               nullable=True)
    op.alter_column('subscriptions', 'reminder_count',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('subscriptions', 'reminder_days',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('subscriptions', 'auto_renew',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('subscriptions', 'status',
               existing_type=sa.VARCHAR(length=9),
               nullable=True)
    op.alter_column('subscriptions', 'currency',
               existing_type=sa.VARCHAR(length=3),
               nullable=True)
    op.alter_column('subscriptions', 'billing_cycle',
               existing_type=sa.VARCHAR(length=9),
               nullable=True)
    op.alter_column('ssl_certificates', 'updated_at',
               existing_type=sa.DATETIME(),
               nullable=True)
    op.alter_column('ssl_certificates', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.alter_column('ssl_certificates', 'reminder_days',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('ssl_certificates', 'renewal_failure_count',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('ssl_certificates', 'currency',
               existing_type=sa.VARCHAR(length=3),
               nullable=True)
    op.alter_column('ssl_certificates', 'annual_cost',
               existing_type=sa.FLOAT(),
               nullable=True)
    op.alter_column('ssl_certificates', 'is_wildcard',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('ssl_certificates', 'auto_renew',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('ssl_certificates', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('ssl_certificates', 'certificate_type',
               existing_type=sa.VARCHAR(length=12),
               nullable=True)
    op.alter_column('ssl_certificates', 'provider',
               existing_type=sa.VARCHAR(length=12),
               nullable=True)
    _add_columns_if_missing(
        inspector,
        'servers',
        [
            sa.Column('panel_api_token', sa.TEXT(), nullable=True),
            sa.Column('panel_api_user', sa.VARCHAR(length=100), nullable=True),
        ],
    )
    op.alter_column('servers', 'panel_verified',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('servers', 'panel_port',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('servers', 'panel_type',
               existing_type=sa.Enum('CYBERPANEL', 'CPANEL', 'PLESK', 'DIRECTADMIN', 'NONE', name='paneltype'),
               type_=sa.VARCHAR(length=10),
               existing_nullable=False)
    _drop_columns_if_exist(
        inspector,
        'servers',
        ['panel_password', 'panel_username', 'ssh_private_key', 'ssh_password'],
    )
    op.alter_column('projects', 'gdrive_connected',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.create_index(op.f('ix_project_servers_server_id'), 'project_servers', ['server_id'], unique=False)
    op.create_index(op.f('ix_project_servers_project_id'), 'project_servers', ['project_id'], unique=False)
    op.alter_column('notification_channels', 'updated_at',
               existing_type=sa.DATETIME(),
               nullable=True)
    op.alter_column('notification_channels', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=True)
    op.alter_column('notification_channels', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('notification_channels', 'channel_type',
               existing_type=sa.VARCHAR(length=8),
               nullable=True)
    op.alter_column('monitors', 'last_status',
               existing_type=sa.Enum('up', 'down', 'degraded', 'pending', 'maintenance', name='monitorstatus'),
               type_=sa.VARCHAR(length=8),
               existing_nullable=True)
    op.alter_column('invoices', 'updated_at',
               existing_type=sa.DATETIME(),
               nullable=True)
    op.alter_column('invoices', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.alter_column('invoices', 'currency',
               existing_type=sa.VARCHAR(length=3),
               nullable=True)
    op.alter_column('invoices', 'amount_paid',
               existing_type=sa.FLOAT(),
               nullable=True)
    op.alter_column('invoices', 'total',
               existing_type=sa.FLOAT(),
               nullable=True)
    op.alter_column('invoices', 'discount_amount',
               existing_type=sa.FLOAT(),
               nullable=True)
    op.alter_column('invoices', 'tax_amount',
               existing_type=sa.FLOAT(),
               nullable=True)
    op.alter_column('invoices', 'tax_rate',
               existing_type=sa.FLOAT(),
               nullable=True)
    op.alter_column('invoices', 'subtotal',
               existing_type=sa.FLOAT(),
               nullable=True)
    op.alter_column('invoices', 'status',
               existing_type=sa.VARCHAR(length=9),
               nullable=True)
    op.alter_column('invoice_items', 'total',
               existing_type=sa.FLOAT(),
               nullable=True)
    op.alter_column('invoice_items', 'unit_price',
               existing_type=sa.FLOAT(),
               nullable=True)
    op.alter_column('invoice_items', 'quantity',
               existing_type=sa.FLOAT(),
               nullable=True)
    op.alter_column('incidents', 'updated_at',
               existing_type=sa.DATETIME(),
               nullable=True)
    op.alter_column('incidents', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=True)
    op.alter_column('incidents', 'recovery_notification_sent',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('incidents', 'notification_sent',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('incidents', 'status',
               existing_type=sa.VARCHAR(length=13),
               nullable=True)
    op.alter_column('hosting_packages', 'updated_at',
               existing_type=sa.DATETIME(),
               nullable=True)
    op.alter_column('hosting_packages', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.alter_column('hosting_packages', 'sort_order',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('hosting_packages', 'is_featured',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('hosting_packages', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('hosting_packages', 'currency',
               existing_type=sa.VARCHAR(length=3),
               nullable=True)
    op.alter_column('hosting_packages', 'setup_fee',
               existing_type=sa.FLOAT(),
               nullable=True)
    op.alter_column('hosting_packages', 'biennial_price',
               existing_type=sa.FLOAT(),
               nullable=True)
    op.alter_column('hosting_packages', 'yearly_price',
               existing_type=sa.FLOAT(),
               nullable=True)
    op.alter_column('hosting_packages', 'quarterly_price',
               existing_type=sa.FLOAT(),
               nullable=True)
    op.alter_column('hosting_packages', 'monthly_price',
               existing_type=sa.FLOAT(),
               nullable=True)
    op.alter_column('hosting_packages', 'cpu_cores',
               existing_type=sa.FLOAT(),
               nullable=True)
    op.alter_column('hosting_packages', 'ram_mb',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('hosting_packages', 'php_workers',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('hosting_packages', 'ftp_accounts_limit',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('hosting_packages', 'email_accounts_limit',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('hosting_packages', 'databases_limit',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('hosting_packages', 'subdomains_limit',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('hosting_packages', 'domains_limit',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('hosting_packages', 'bandwidth_gb',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('hosting_packages', 'disk_space_gb',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('heartbeats', 'checked_at',
               existing_type=sa.DATETIME(),
               nullable=True)
    op.alter_column('heartbeats', 'status',
               existing_type=sa.VARCHAR(length=8),
               nullable=True)
    op.alter_column('domains', 'updated_at',
               existing_type=sa.DATETIME(),
               nullable=True)
    op.alter_column('domains', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.alter_column('domains', 'reminder_days',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('domains', 'currency',
               existing_type=sa.VARCHAR(length=3),
               nullable=True)
    op.alter_column('domains', 'annual_cost',
               existing_type=sa.FLOAT(),
               nullable=True)
    op.alter_column('domains', 'transfer_lock',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('domains', 'privacy_protection',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('domains', 'auto_renew',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('domains', 'status',
               existing_type=sa.VARCHAR(length=16),
               nullable=True)
    op.alter_column('domains', 'registrar',
               existing_type=sa.VARCHAR(length=14),
               nullable=True)
    _add_columns_if_missing(
        inspector,
        'clients',
        [
            sa.Column('contract_terms', sa.TEXT(), nullable=True),
            sa.Column('website', sa.VARCHAR(length=500), nullable=True),
            sa.Column('monthly_retainer', sa.FLOAT(), nullable=True),
        ],
    )
    op.drop_constraint(None, 'clients', type_='foreignkey')
    clients_email_index = op.f('ix_clients_email')
    if _index_exists(inspector, 'clients', clients_email_index):
        op.drop_index(clients_email_index, table_name='clients')
    op.create_index(op.f('ix_clients_email'), 'clients', ['email'], unique=1)
    op.alter_column('clients', 'updated_at',
               existing_type=sa.DATETIME(),
               nullable=True)
    op.alter_column('clients', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.alter_column('clients', 'next_invoice_number',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('clients', 'invoice_prefix',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.alter_column('clients', 'auto_billing',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('clients', 'tax_rate',
               existing_type=sa.FLOAT(),
               nullable=True)
    op.alter_column('clients', 'currency',
               existing_type=sa.VARCHAR(length=3),
               nullable=True)
    op.alter_column('clients', 'payment_terms',
               existing_type=sa.String(length=50),
               type_=sa.INTEGER(),
               nullable=True)
    op.alter_column('clients', 'billing_status',
               existing_type=sa.Enum('ACTIVE', 'INACTIVE', 'TRIAL', 'OVERDUE', 'CANCELLED', name='billingstatus'),
               type_=sa.VARCHAR(length=8),
               nullable=True)
    _drop_columns_if_exist(
        inspector,
        'clients',
        [
            'owner_id',
            'tags',
            'last_payment_date',
            'last_invoice_date',
            'outstanding_balance',
            'total_revenue',
            'monthly_rate',
            'country',
            'postal_code',
            'state',
            'city',
            'billing_name',
        ],
    )
    op.alter_column('client_users', 'updated_at',
               existing_type=sa.DATETIME(),
               nullable=True)
    op.alter_column('client_users', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=True)
    op.alter_column('client_users', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    # ### end Alembic commands ###
